openapi: 3.0.0
info:
  title: Flashcards API
  version: 1.0.0
  description: API for managing and rating flashcards

paths:
  /api/flashcards:
    get:
      summary: Get all flashcards (excluding hidden ones)
      responses:
        '200':
          description: List of flashcards
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    question:
                      type: string
                    answer:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    hidden:
                      type: boolean
        '500':
          description: Server error

  /api/flashcards/{id}/hide:
    post:
      summary: Hide a flashcard by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Flashcard hidden successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error

  /api/flashcards/rate:
    post:
      summary: Rate a flashcard set
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                setId:
                  type: integer
                  description: ID of the flashcard set to rate
                rating:
                  type: integer
                  description: Rating value between 1 and 5
                  minimum: 1
                  maximum: 5
      responses:
        '201':
          description: Rating added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid rating
        '500':
          description: Server error

  /api/flashcards/top-rated:
    get:
      summary: Get top-rated flashcard sets
      responses:
        '200':
          description: List of top-rated flashcard sets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    set_id:
                      type: integer
                    avg_rating:
                      type: number
                      format: float
        '500':
          description: Server error
